services:
  mongodb:
    image: mongo:7.0
    container_name: google-docs-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: googleDocsPassword123
      MONGO_INITDB_DATABASE: google-docs-clone
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    command: mongod --auth

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local